### ISSUE TITLE
Homepage: Vet section description should follow the design.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#11]
Font-family: Arial
Font-size: 14px
Color: #7c8a94

![image](https://cloud.githubusercontent.com/assets/18027230/14060698/1600baf2-f3a7-11e5-97c9-e65b6ad96cb9.png)

**Comment by maehtitan** [comment]
Font-size already achieved but not in the font-color
![image](https://cloud.githubusercontent.com/assets/13363508/14240809/52fd20ce-fa7a-11e5-8fc0-1f2a92683fb1.png)
