### ISSUE TITLE
W3C Checking - Homepage: 5 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/The-Unusual-Vet#118]
https://validator.w3.org/nu/?doc=http%3A%2F%2Funusualpetvets-tmp.stage.titanweb.com.au%2F
![image](https://cloud.githubusercontent.com/assets/13363508/14481335/8ac6c8fc-0164-11e6-9b40-ca8a648569b2.png)

**Comment by algericotitandigital** [comment]
This is an issue on fb plugin.
