### ISSUE TITLE
W3C Checking - Species Single: 3 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/The-Unusual-Vet#119]
https://validator.w3.org/nu/?doc=http%3A%2F%2Funusualpetvets-tmp.stage.titanweb.com.au%2Fvets-list%2Fspecies-02%2F
![image](https://cloud.githubusercontent.com/assets/13363508/14481367/de8e5248-0164-11e6-9dc4-f29d2e2b9713.png)

**Comment by algericotitandigital** [comment]
This is a plugin issue.
