### ISSUE TITLE
W3C Checking - Product Listing: 7 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/The-Unusual-Vet#120]
https://validator.w3.org/nu/?doc=http%3A%2F%2Funusualpetvets-tmp.stage.titanweb.com.au%2Fproduct-category%2Ftest-main-category%2Ftest-sub-category%2F
![image](https://cloud.githubusercontent.com/assets/13363508/14481398/2a70c632-0165-11e6-9998-6f9adb483909.png)

**Comment by algericotitandigital** [comment]
The rest of the errors are due to plugin.
