### ISSUE TITLE
Homepage - Vets: Isn't working properly in responsive view, it doesn't auto rotate and alignment problem found

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/The-Unusual-Vet#123]
and it looks like this in 1200 view port size
![image](https://cloud.githubusercontent.com/assets/13363508/14482599/09585de6-0171-11e6-8af3-5f639304a78e.png)

**Comment by algericotitandigital** [comment]
try to use the natural browser not mobile emulator in 1200px, I think, we can use mobile emulator for small devices and ipads. 1200px resolution is a size of a laptop.
