### ISSUE TITLE
General: Gravity Form label/placeholder color did not follow the design.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#18]

**Comment by maehtitan** [comment]
Not yet fixed.
![image](https://cloud.githubusercontent.com/assets/13363508/14240120/deeb327a-fa74-11e5-8c05-51c9fcd42862.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14240138/00bb2658-fa75-11e5-9648-87152a5ad199.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14240167/35353518-fa75-11e5-8637-d77a7f0e536d.png)
