### ISSUE TITLE
Header: Align the arrow of the sub-menu and sidebar at the center.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#35]
![screenshot 2016-03-28 20 44 36](https://cloud.githubusercontent.com/assets/18027230/14078183/39b64842-f526-11e5-93d9-38bd44124c14.png)

![screenshot 2016-03-28 20 53 36](https://cloud.githubusercontent.com/assets/18027230/14078315/644391ea-f527-11e5-9da0-a05246d64c45.png)

**Comment by maehtitan** [comment]
Not yet fixed
