### ISSUE TITLE
Our Staff page: Back to top button should be at the bottom part of the image if the content is short as per the design.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#38]
This is also applicable to Our Facilities and Services page.

![screenshot 2016-03-28 21 35 56](https://cloud.githubusercontent.com/assets/18027230/14079112/d50edd02-f52d-11e5-96b4-a0462b59eff9.png)

![screenshot 2016-03-28 21 42 51](https://cloud.githubusercontent.com/assets/18027230/14079472/a1912a22-f530-11e5-8f52-f89a12fd17fa.png)

**Comment by maehtitan** [comment]
Not yet fixed
