### ISSUE TITLE
Sidebar: The sidebar should be aligned with the content as per the given design.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#39]
![screenshot 2016-03-28 22 36 07](https://cloud.githubusercontent.com/assets/18027230/14080185/f6e832d6-f535-11e5-85cf-d7fbdac6f29a.png)

**Comment by maehtitan** [comment]
Not yet fixed.
![image](https://cloud.githubusercontent.com/assets/13363508/14241569/89dcd1c6-fa7e-11e5-8dfa-6aaafefae3ab.png)
