### ISSUE TITLE
Species Single page: The sidebar should align with the content area.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#48]
![image](https://cloud.githubusercontent.com/assets/18027230/14127881/0d0c106e-f64e-11e5-8ad2-d611fc8da874.png)

**Comment by maehtitan** [comment]
Our Staff - ![image](https://cloud.githubusercontent.com/assets/13363508/14242372/34fbaa42-fa83-11e5-9f96-e67ddd018781.png)

News and News Single - ![image](https://cloud.githubusercontent.com/assets/13363508/14242471/6c523100-fa83-11e5-9cc0-6b08ee4c5cd3.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14242552/9be1d75e-fa83-11e5-9d64-965f2be55b77.png)
FAQ - 
![image](https://cloud.githubusercontent.com/assets/13363508/14242579/ba479eea-fa83-11e5-886c-8462d0ee9b9e.png)

And all other affected pages
