### ISSUE TITLE
Homepage: Clipped texts in the Vet section.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#6]
![image](https://cloud.githubusercontent.com/assets/18027230/14058021/fb9a720c-f34c-11e5-9945-f5f493832db2.png)

![image](https://cloud.githubusercontent.com/assets/18027230/14060684/d3faa3b6-f3a6-11e5-887e-282b7b74ea69.png)

**Comment by maehtitan** [comment]
Not yet fixed
![image](https://cloud.githubusercontent.com/assets/13363508/14237716/40cf5fae-fa5a-11e5-92ca-2ba7bf3b961a.png)
