### ISSUE TITLE
Banner: There should be no fall back value for "Play Video".

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#7]

**Comment by maehtitan** [comment]
Removing the Button text label should completely hide the button
![image](https://cloud.githubusercontent.com/assets/13363508/14238577/7ee5f658-fa65-11e5-902e-f107769f0f6d.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14238590/9bc0f2dc-fa65-11e5-8198-f9e7807a0a92.png)

**Comment by maehtitan** [comment]
@algericotitandigital No changes has been been still there is a fallback implemented.
![image](https://cloud.githubusercontent.com/assets/13363508/14481680/e59bb258-0167-11e6-93d4-392640141c94.png)
