### ISSUE TITLE
Homepage: Vet section seems broken.

### ISSUE THREAD

**Issue by joancapuyan** [titan-cebu/The-Unusual-Vet#8]
![image](https://cloud.githubusercontent.com/assets/18027230/14060216/f877b17a-f397-11e5-83fb-4156aefb8453.png)

**Comment by maehtitan** [comment]
Not yet fixed
![image](https://cloud.githubusercontent.com/assets/13363508/14241240/05bc5688-fa7d-11e5-96d4-75b0ea034598.png)

**Comment by maehtitan** [comment]
@algericotitandigital not yet fixed
![image](https://cloud.githubusercontent.com/assets/13363508/14482657/7672cdc6-0171-11e6-9cd5-d414b2d224b9.png)
