### ISSUE TITLE
Product Single: Missing magnifying glass icon which supposedly the clickable elements to view in a fancy box pop up

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/The-Unusual-Vet#94]
![image](https://cloud.githubusercontent.com/assets/13363508/14306572/ecca6136-fbfa-11e5-841a-ecc2bf977f9c.png)

**Comment by algericotitandigital** [comment]
We can't modify the anchor tag because there's is a possibility that links on images for variation will not work.
